device: "cuda:1"

model:
  name: "deta"
  model_name: "theodullin/deta-resnet-50_finetuned_blood_cell_10epochs"
  _name_or_path: "theodullin/deta-resnet-50_finetuned_blood_cell_10epochs"
  activation_dropout: 0.27
  activation_function: "relu"
  assign_first_stage: false
  attention_dropout: 0.11
  auxiliary_loss: true
  backbone_config:
    model_type: "resnet"
    out_features: ["stage2", "stage3", "stage4"]
    out_indices: [2, 3, 4]
  bbox_cost: 4
  bbox_loss_coefficient: 5.28
  class_cost: 1.75
  d_model: 256
  decoder_attention_heads: 8
  decoder_ffn_dim: 2048
  decoder_layerdrop: 0.0
  decoder_layers: 6
  decoder_n_points: 8
  dice_loss_coefficient: 1
  dropout: 0.12
  encoder_attention_heads: 8
  encoder_ffn_dim: 2048
  encoder_layerdrop: 0.0
  encoder_layers: 6
  encoder_n_points: 4
  eos_coefficient: 0.11
  focal_alpha: 0.25
  giou_cost: 1.75
  giou_loss_coefficient: 6.65
  init_std: 0.02
  init_xavier_std: 1.0
  is_encoder_decoder: true
  mask_loss_coefficient: 1
  max_position_embeddings: 2048
  num_feature_levels: 5
  position_embedding_type: "sine"
  two_stage: true
  two_stage_num_proposals: 350
  with_box_refine: true

processor:
  model_name: "theodullin/deta-resnet-50_finetuned_blood_cell_10epochs"
  do_normalize: true
  do_pad: false
  do_rescale: false
  do_resize: false
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]
  resample: 2
  rescale_factor: 0.00392156862745098
  width: 960
  height: 540

transforms:
  train:
    hflip_prob: 0.38
    vflip_prob: 0.10
    rotate_prob: 0.49
    rotate_degrees: 145.01
    blur_prob: 0.47
    blur_kernel_size: [9, 9]
    blur_sigma: [0.5, 1.0]
    brightness: 0.11
    contrast: 0.16
    saturation: 0.5
    hue: 0.165
    color_jitter_prob: 0.27
    gray_prob: 0.22
    crop_prob: 0.38
    crop_scale_min: 0.68
    crop_scale_max: 1.01
    plasma_brightness_roughness: [0.5, 0.5]
    plasma_brightness_prob: 0.17
    posterize_bits: 7
    posterize_prob: 0.18
    saturation_prob: 0.09
    solarize_threshold: 0.90
    solarize_addition: 0.09
    solarize_prob: 0.24
    affine_degrees: [-15, 15]
    affine_translate: [0.1, 0.1]
    affine_scale: [0.8, 1.2]
    affine_shear: [-5, 5]
    affine_prob: 0.33
    hue_range: [-0.5, 0.5]
    hue_prob: 0.20
    sharpness: 0.27
    sharpness_prob: 0.01
  validation: {}

testing:
  test_batch_size: 4
  save_images: false
  num_images_to_save: 0
  confidence_threshold: 0

training:
  train_batch_size: 4
  n_accum: 3
  num_epochs: 5
  learning_rate: 0.0004630770829815448
  warmup_steps: 1200

ema:
  enabled: true
  beta: 0.9999
  update_after_step: 100
  update_every: 1